### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sirvine** [dougc84/carrierwave_securefile#1]
Hi Doug,

I've just dropped carrierwave_securefile into an app, and experienced the following:
1.  When I upload a file, it appears in `/public/uploads/tmp/<datestamp>/<filename>`
2.  On the server, the development log shows `Uploading using Crypt::Blowfish...`
3.  Then the server throws 500 error with a message: Errno::ENOENT (No such file or directory - (/uploads/tmp/20120323-1732-96805-4492/original_filename.pdf, /uploads/tmp/20120323-1732-96805-4492/original_filename.pdf.x1))

It looks to me like the File.rename call in the carrierwave_securefile uploader.rb file is failing, although the original file should be at the indicated uploads/tmp path.

Any ideas?

Thanks!

**Comment by sirvine** [comment]
UPDATE:  I managed to work around this by passing `@file.path` instead of `self`.  Maybe the relative path behavior is different in newer versions of Rails?

Anyway, this worked:

```
def secure_file
    CarrierWave::SecureFile::Uploader.secure_file( model, @file.path.to_s )
end
```

BTW, the same issue bit me on the download side.  Since the path isn't a parameter there, I forked to change it to `file = downloader.file.path.to_s`.

**Comment by dougc84** [comment]
awesome... you fixed the issue before i even got around to looking at your request.  that's commitment.  send me a pull request and i'll push the changes.

**Comment by designhunger** [comment]
Hi sirvine,
I forked the repo, too. But I could not get the downloader to work with the subsitution of the file line. Did you change anything else, too?
Thanks!

**Comment by sirvine** [comment]
I'm still working my way through this solution.  I'm not sure it's ready for a PR, honestly.  I'll focus on it this weekend, and clean it up for a PR.

@designhunger I didn't have any problem with uploads, as long as I passed `@file.path.to_s` as above.  However, I forked the repo to handle downloads, which required a change to the internals.

In your uploader, are you seeing the expected absolute path at `@file.path`?

**Comment by designhunger** [comment]
@sirvine The upload process is working pretty good, but I'm struggeling with the download. This line in the download library is not working:
downloader.download!(filename)
So it thorughs an exception and ends with the error code already posted by you:
Errno::ENOENT (No such file or directory - (/uploads/attachment/file/8/business-model-canvas.png, /uploads/attachment/file/8/business-model-canvas.png.x1)):

Do you have any idea whats going on there?
Thanks!

**Comment by sirvine** [comment]
@designhunger Are you using the latest version of this gem?  @dougc84 pulled in some changes from my fork recently.

**Comment by dougc84** [comment]
since this is over a month old, i'm closing this ticket.
